"""feat: agregar modelo PaymentHistory

Revision ID: 488e9a013d48
Revises: fc5d4b7303b7
Create Date: 2026-04-23 15:32:05.067803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488e9a013d48'
down_revision = 'fc5d4b7303b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', name='history_payment_method_enum'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    # ### end Alembic commands ###
